version: '3'
services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  python-app:
    image: python:3.9-alpine
    volumes:
      - ./pkgs/python:/app
    working_dir: /app
    command: ["python", "script.py"]
